# Generated by Django 5.1.6 on 2025-02-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uchet1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predmets',
            name='ind',
        ),
    ]
