# Generated by Django 5.1.6 on 2025-02-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet1', '0003_alter_predmets_hours_1sem_alter_predmets_hours_2sem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmets',
            name='hours_1sem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predmets',
            name='hours_2sem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predmets',
            name='hours_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predmets',
            name='hours_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predmets',
            name='hours_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predmets',
            name='pairs_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SemesterGrade',
        ),
    ]
