# Generated by Django 5.1.6 on 2025-02-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet1', '0004_alter_predmets_hours_1sem_alter_predmets_hours_2sem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Семестр'),
        ),
        migrations.AddField(
            model_name='pa',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Семестр'),
        ),
    ]
