# Generated by Django 5.1.6 on 2025-02-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet1', '0006_customuser_prepod'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmets',
            name='zachot',
            field=models.BooleanField(default=0),
        ),
    ]
